# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/smartcampus

# Security Configuration
# JWT Secret (Should be moved to environment variables for production)
app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwtExpirationMs=86400000

# JPA/Hibernrate (Disable if not using SQL)
# spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
